name: TGZ_hello
on: 
 push
 # tags:
 #  - "*TGZ*"
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v1
   - name: build hello_world_application
     run: |
      cd hello_world_application
      cmake -B applications
      cmake --build applications --target hello_world
      ./applications/hello_world > hello.txt
      cat hello.txt
      cd ..
   - name: 'Upload Artifact'
     uses: actions/upload-artifact@v3
     with:
       name: hello_world
       path: |
         ./hello_world_application/hello.txt
   - name: download-artifact
     uses: actions/download-artifact@v3
     with:
       name: hello_world
       path: ./artifact
    
   - name: Display structure of downloaded files
     run: |
       ls -R
       cd ./artifact
       cat hello.txt
     working-directory: ./artifact
         
