name: TGZ_hello
on: 
 push
 # tags:
 #  - "*TGZ*"
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
  
   - name: git clone
     uses: actions/checkout@v1
     
   - name: build hello_world_application
     run: |
      cd hello_world_application
      cmake -B applications
      cmake --build applications --target hello_world
      ./applications/hello_world > hello.txt
      cat hello.txt
      cd ..
      
   - name: Upload Artifact v1
     uses: actions/upload-artifact@v3
     with:
       name: hello_world
       path: |
         ./hello_world_application/hello.txt
         
   - name: download-artifact v1
     uses: actions/download-artifact@v3
     with:
       name: hello_world
       path: ./artifact
       
   - name: Display structure of downloaded files v1
     run: |
       ls -R
       cat hello.txt
     working-directory: ./artifact
     
   - name: Upload Artifact v2
     uses: actions/upload-artifact@v3
     with:
       name: cpp
       path: |
         ./hello_world_application/hello_world.cpp
         ./solver_application/equation.cpp  

   - name: download-artifact v2
     uses: actions/download-artifact@v3
     with:
       name: cpp
       path: ./artifact
       
   - name: Display structure of downloaded files v2
     run: |
       ls -R
     working-directory: ./artifact
